### ISSUE TITLE
Failed build for 5 columns view-zmk-config template

### ISSUE THREAD

**Issue by DanielAtCosmicDNA** [typeractivexyz/corne-wireless-5-col-view-zmk-config#6]
The build from the template is currently failiing as can be observed at https://github.com/CosmicDNA/corne-wireless-5-col-view-zmk-config/actions/runs/10813360993.

**Comment by Azereal08** [comment]
I've got the same issue.  if it could be fixed that would be great. Someone said it was a change in zmk somewhere, but I don't really know exactly

**Comment by DanielAtCosmicDNA** [comment]
The following error is shown:

>    17 | #error "To use physical layouts, remove the chosen `zmk,matrix-transform` value."
>       |  ^~~~~
> compilation terminated due to -Wfatal-errors.

And [here is the offending line](https://github.com/CosmicDNA/corne-wireless-5-col-view-zmk-config/blob/master/config/corne.keymap#L16).
